### ISSUE TITLE
Error x64 version.

### ISSUE THREAD

**Issue by ramoneeza** [strobejb/winspy#3]
x64 version error access denied. 

static LRESULT CALLBACK URLCtrlProc(HWND hwnd, UINT iMsg, WPARAM wParam, LPARAM lParam)
{
    PAINTSTRUCT ps;
    HDC     hdc;

```
    URLCtrl *url = (URLCtrl *)GetWindowLongPtr(hwnd, GWLP_USERDATA);
    WNDPROC oldproc = url->oldproc;
```

**Comment by RaMMicHaeL** [comment]
You can try [my fork](https://github.com/RaMMicHaeL/winspy/releases), which works properly on x64 :)

**Comment by strobejb** [comment]
m417z's fixes have been finally merged, so closing this as fixed
